module TicketParserTests exposing (..)

import Array
import DateTime exposing (DateTime)
import Expect
import Test exposing (..)
import Ticket
import TicketParser


suite : Test
suite =
    describe "TicketParser"
        [ test "parses a regular ticket correctly" <|
            \_ ->
                let
                    expectedTicket =
                        { departureStation = "Foo"
                        , arrivalStation = "Bar"
                        , departure = DateTime 2018 11 4 13 25
                        , arrival = DateTime 2018 11 4 20 22
                        , train = "TLK 12345"
                        , carriage = "13"
                        , seat = "35o"
                        }
                in
                TicketParser.parseStrings regularTicketStrings
                    |> Expect.equal (Ok expectedTicket)
        , test "handles a returned ticket with arrival on a different day than departure" <|
            \_ ->
                let
                    expectedTicket =
                        { departureStation = "Foo"
                        , arrivalStation = "Bar"
                        , departure = DateTime 2018 12 28 12 25
                        , arrival = DateTime 2018 12 29 21 17
                        , train = "TLK 12345"
                        , carriage = "10"
                        , seat = "25o"
                        }
                in
                TicketParser.parseStrings differentDaysTicketStrings
                    |> Expect.equal (Ok expectedTicket)
        , test "handles a double ticket" <|
            \_ ->
                let
                    expectedTicket =
                        { departureStation = "Foo"
                        , arrivalStation = "Bar"
                        , departure = DateTime 2019 8 4 12 12
                        , arrival = DateTime 2019 8 4 21 17
                        , train = "TLK 12345"
                        , carriage = "10"
                        , seat = "56o, 55o"
                        }
                in
                TicketParser.parseStrings doubleTicketStrings
                    |> Expect.equal (Ok expectedTicket)
        , test "handles a ticket bought for the next year" <|
            \_ ->
                let
                    expectedTicket =
                        { departureStation = "Foo"
                        , arrivalStation = "Bar"
                        , departure = DateTime 2020 1 1 23 14
                        , arrival = DateTime 2020 1 2 9 15
                        , train = "EIP 1234"
                        , carriage = "2"
                        , seat = "32o"
                        }
                in
                TicketParser.parseStrings ticketForNextYear
                    |> Expect.equal (Ok expectedTicket)
        ]


regularTicketStrings =
    Array.fromList
        [ "Data wydruku: 2019-11-01 21:27:24"
        , "12345"
        , "NORMAL. : "
        , "1"
        , "ULG. : "
        , "   X : X"
        , " OF: 1"
        , "\"PKP Intercity\""
        , "Spółka Akcyjna"
        , "Przewoźnik: PKP IC"
        , "BILET INTERNETOWY"
        , "E-Wcześniej: 1xNormal"
        , "¦"
        , " ̧"
        , "Od/From "
        , ""
        , "Do/To"
        , "¦"
        , " ̧"
        , "KL./CL."
        , "04.11"
        , "*"
        , "13:25"
        , "*"
        , "Foo"
        , "*"
        , ""
        , "Bar"
        , "*"
        , "04.11"
        , "*"
        , "20:22"
        , "*"
        , "2"
        , "*"
        , "PRZEZ: Quux * Baz"
        , "SUMA PLN:"
        , "48,00 zł"
        , "130983210984"
        , "Nr biletu"
        , ": eIC13289321"
        , "(P24) 1239"
        , "Informacje o podróży:"
        , "Stacja"
        , "Data"
        , "Godzina"
        , "/Wagon"
        , "Km"
        , "Nr miejsca"
        , " (o-okno ś-środek k-korytarz)"
        , "Suma PLN"
        , "Foo"
        , "Bar"
        , "04.11"
        , "04.11"
        , "13:25"
        , "20:22"
        , "TLK 12345"
        , "13"
        , "122"
        , "35o"
        , "1 m. do siedzenia; wagon z przedziałami"
        , "32,00 zł"
        , "r4I"
        , "r4I"
        , "Podróżny: Fuuux Buuuuux"
        , "Informacja o cenie"
        , "PTU"
        , "Suma PLN"
        , "Płatność: przelewem"
        , "Opłata za przejazd:"
        , " 8%"
        , "32,00"
        , "Zapłacono i wystawiono dnia:"
        , "2018-10-21 12:12:29(11111111)"
        , "Ogółem PLN:"
        , "32,00"
        , "Bilet internetowy jest biletem imiennym i jest ważny:"
        , "a) wraz z dokumentem ze zdjęciem potwierdzającym tożsamość Podróżnego,"
        , "b) tylko w dniu, relacji, pociągu, wagonie i na miejsce na nim oznaczone."
        , "Zwrotu należności za niewykorzystany bilet dokonuje się na podstawie wniosku"
        , "złożonego przez płatnika w wyznaczonych przez 'PKP Intercity' S.A. punktach, z"
        , "wyjątkiem należności zwracanych automatycznie na zasadach określonych w"
        , "Regulaminie e-IC."
        , "Niniejszy bilet internetowy nie jest fakturą VAT."
        , "W związku z przeprowadzanymi modernizacjami sieci kolejowej, uprzejmie prosimy o"
        , "dokładne sprawdzanie rozkładu jazdy pociągów przed podróżą."
        ]


differentDaysTicketStrings =
    Array.fromList
        [ "Data wydruku: 2019-11-01 21:28:41"
        , "12345"
        , "NORMAL. : "
        , "1"
        , "ULG. : "
        , "   X : X"
        , " OF: 1"
        , "Rezygnacja z zakupu wykonana przez użytkownika - Bilet zwrócony "
        , "\"PKP Intercity\""
        , "Spółka Akcyjna"
        , "Przewoźnik: PKP IC"
        , "BILET INTERNETOWY"
        , "E-Wcześniej: 1xNormal"
        , "¦"
        , " ̧"
        , "Od/From "
        , ""
        , "Do/To"
        , "¦"
        , " ̧"
        , "KL./CL."
        , "28.12"
        , "*"
        , "12:25"
        , "*"
        , "Foo"
        , "*"
        , ""
        , "Bar"
        , "*"
        , "29.12"
        , "*"
        , "21:17"
        , "*"
        , "2"
        , "*"
        , "PRZEZ: Fix * Flix"
        , "SUMA PLN:"
        , "42,00 zł"
        , "123081239821"
        , "Nr biletu"
        , ": eIC12398231"
        , "(P24) 1123"
        , "Informacje o podróży:"
        , "Stacja"
        , "Data"
        , "Godzina"
        , "/Wagon"
        , "Km"
        , "Nr miejsca"
        , " (o-okno ś-środek k-korytarz)"
        , "Suma PLN"
        , "Foo"
        , "Bar"
        , "28.12"
        , "29.12"
        , "12:25"
        , "21:17"
        , "TLK 12345"
        , "10"
        , "292"
        , "25o"
        , "1 m. do siedzenia; wagon z przedziałami"
        , "23,00 zł"
        , "r2I"
        , "r2I"
        , "Podróżny: Fuuux Baaaaaz"
        , "Informacja o cenie"
        , "PTU"
        , "Suma PLN"
        , "Płatność: przelewem"
        , "Opłata za przejazd:"
        , " 8%"
        , "23,00"
        , "Zapłacono i wystawiono dnia:"
        , "2018-12-09 19:11:40(12345678)"
        , "Ogółem PLN:"
        , "23,00"
        , "Zrezygnowano z przejazdu w dniu:"
        , "2018-12-18 o godz.  12:01:34"
        , "Kod rezygnacji: 123443"
        , "Kwota zwrotu ogółem: 20,80 zł"
        , "Data zwrotu: 2018-12-18 12:01:48"
        , "Przyczyna zwrotu biletu: Zwrot przez klienta"
        , "Bilet internetowy jest biletem imiennym i jest ważny:"
        , "a) wraz z dokumentem ze zdjęciem potwierdzającym tożsamość Podróżnego,"
        , "b) tylko w dniu, relacji, pociągu, wagonie i na miejsce na nim oznaczone."
        , "Zwrotu należności za niewykorzystany bilet dokonuje się na podstawie wniosku"
        , "złożonego przez płatnika w wyznaczonych przez 'PKP Intercity' S.A. punktach, z"
        , "wyjątkiem należności zwracanych automatycznie na zasadach określonych w"
        , "Regulaminie e-IC."
        , "Niniejszy bilet internetowy nie jest fakturą VAT."
        , "W związku z przeprowadzanymi modernizacjami sieci kolejowej, uprzejmie prosimy o"
        , "dokładne sprawdzanie rozkładu jazdy pociągów przed podróżą."
        ]


doubleTicketStrings =
    Array.fromList
        [ "Data wydruku: 2019-11-01 21:30:03"
        , "12345"
        , "NORMAL. : "
        , "2"
        , "ULG. : "
        , "   X : X"
        , " OF: 1"
        , "\"PKP Intercity\""
        , "Spółka Akcyjna"
        , "Przewoźnik: PKP IC"
        , "BILET INTERNETOWY"
        , "C-Wcześniej: 2xNormal"
        , "¦"
        , " ̧"
        , "Od/From "
        , ""
        , "Do/To"
        , "¦"
        , " ̧"
        , "KL./CL."
        , "04.08"
        , "*"
        , "12:12"
        , "*"
        , "Foo"
        , "*"
        , ""
        , "Bar"
        , "*"
        , "04.08"
        , "*"
        , "21:17"
        , "*"
        , "2"
        , "*"
        , "PRZEZ: Baz * Quux"
        , "SUMA PLN:"
        , "34,00 zł"
        , "213981223111"
        , "Nr biletu"
        , ": eIC12332123"
        , "(P24) 1212"
        , "Informacje o podróży:"
        , "Stacja"
        , "Data"
        , "Godzina"
        , "/Wagon"
        , "Km"
        , "Nr miejsca"
        , " (o-okno ś-środek k-korytarz)"
        , "Suma PLN"
        , "Foo"
        , "Bar"
        , "04.08"
        , "04.08"
        , "12:12"
        , "21:17"
        , "TLK 12345"
        , "10"
        , "191"
        , "56o, 55o"
        , "2 m. do siedzenia; wagon bez przedziałów"
        , "34,00 zł"
        , "Bilet, w dniu ważności, uprawnia do przejazdu bez dodatkowych opłat od st. Kraków: Gł."
        , "do Pł w poc. PKP IC (oprócz EIP) i wybranymi tramwajami ZTP  – spr. na intercity.pl"
        , "r0L"
        , "r0L"
        , "Podróżny: Fuuux Quuuuux"
        , "Informacja o cenie"
        , "PTU"
        , "Suma PLN"
        , "Płatność: przelewem"
        , "Opłata za przejazd:"
        , " 8%"
        , "34,00"
        , "Zapłacono i wystawiono dnia:"
        , "2019-07-09 11:41:32(11231233)"
        , "Ogółem PLN:"
        , "34,00"
        , "Bilet internetowy jest biletem imiennym i jest ważny:"
        , "a) wraz z dokumentem ze zdjęciem potwierdzającym tożsamość Podróżnego,"
        , "b) tylko w dniu, relacji, pociągu, wagonie i na miejsce na nim oznaczone."
        , "Zwrotu należności za niewykorzystany bilet dokonuje się na podstawie wniosku"
        , "złożonego przez płatnika w wyznaczonych przez 'PKP Intercity' S.A. punktach, z"
        , "wyjątkiem należności zwracanych automatycznie na zasadach określonych w"
        , "Regulaminie e-IC."
        , "Niniejszy bilet internetowy nie jest fakturą VAT."
        , "W związku z przeprowadzanymi modernizacjami sieci kolejowej, uprzejmie prosimy o"
        , "dokładne sprawdzanie rozkładu jazdy pociągów przed podróżą."
        ]


ticketForNextYear =
    Array.fromList
        [ "Data wydruku: 2019-11-01 21:32:31"
        , "1234"
        , "NORMAL. : "
        , "1"
        , "ULG. : "
        , "   X : X"
        , " OF: 1"
        , "\"PKP Intercity\""
        , "Spółka Akcyjna"
        , "Przewoźnik: PKP IC"
        , "BILET INTERNETOWY"
        , "B-SuperPromo: 1xNormal"
        , "¦"
        , " ̧"
        , "Od/From "
        , ""
        , "Do/To"
        , "¦"
        , " ̧"
        , "KL./CL."
        , "01.01"
        , "*"
        , "23:14"
        , "*"
        , "Foo"
        , "*"
        , ""
        , "Bar"
        , "*"
        , "02.01"
        , "*"
        , "09:15"
        , "*"
        , "1"
        , "*"
        , "PRZEZ: Baz"
        , "SUMA PLN:"
        , "119,00 zł"
        , "123456123556"
        , "Nr biletu"
        , ": eIC12312343"
        , "(P24) 1111"
        , "Informacje o podróży:"
        , "Stacja"
        , "Data"
        , "Godzina"
        , "/Wagon"
        , "Km"
        , "Nr miejsca"
        , " (o-okno ś-środek k-korytarz)"
        , "Suma PLN"
        , "Foo"
        , "Bar"
        , "01.01"
        , "02.01"
        , "23:14"
        , "09:15"
        , "EIP 1234"
        , "2"
        , "293"
        , "32o"
        , "1 m. do siedzenia; wagon bez przedziałów"
        , "119,00 zł"
        , "Bilet, w dniu ważności, uprawnia do przejazdu bez dodatkowych opłat od st. Kraków: Pł."
        , "do Gł. w poc. PKP IC (oprócz EIP) i wybranymi tramwajami ZTP  – spr. na intercity.pl"
        , "r2R"
        , "r2R"
        , "Podróżny: Rafał Cieślak"
        , "Informacja o cenie"
        , "PTU"
        , "Suma PLN"
        , "Płatność: przelewem"
        , "Opłata za przejazd:"
        , " 8%"
        , "119,00"
        , "Zapłacono i wystawiono dnia:"
        , "2019-10-20 12:29:31(11111111)"
        , "Ogółem PLN:"
        , "119,00"
        , "Bilet internetowy jest biletem imiennym i jest ważny:"
        , "a) wraz z dokumentem ze zdjęciem potwierdzającym tożsamość Podróżnego,"
        , "b) tylko w dniu, relacji, pociągu, wagonie i na miejsce na nim oznaczone."
        , "Zwrotu należności za niewykorzystany bilet dokonuje się na podstawie wniosku"
        , "złożonego przez płatnika w wyznaczonych przez 'PKP Intercity' S.A. punktach, z"
        , "wyjątkiem należności zwracanych automatycznie na zasadach określonych w"
        , "Regulaminie e-IC."
        , "Niniejszy bilet internetowy nie jest fakturą VAT."
        , "W związku z przeprowadzanymi modernizacjami sieci kolejowej, uprzejmie prosimy o"
        , "dokładne sprawdzanie rozkładu jazdy pociągów przed podróżą."
        ]
